{{- if .Values.auth.krb5 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.krb5Config }}
data:
  krb5.conf: |+
    [logging]
    {{- range $key, $value := .Values.auth.krb5.logging }}
    {{ printf "    %s = %s" $key $value }}
    {{- end }}

    [libdefaults]
    {{- range $key, $value := .Values.auth.krb5.libdefaults }}
    {{ printf "    %s = %s" $key $value }}
    {{- end }}

    [realms]
    {{- range $realm, $realmConfig := .Values.auth.realms }}
    {{ printf "    %s = {" $realm }}
    {{ printf "      admin_server = %s" $realmConfig.admin_server }}
    {{- range $realmConfig.kdcs }}
    {{ printf "      kdc = %s" . }}
    {{- end }}
    {{ printf "    }" }}
    {{- end }}

    [domain_realm]
    {{- range $name, $domain := .Values.auth.krb5.domain_realm }}
    {{ printf "    %s = %s" $name $domain }}
    {{- end }}
{{- end }}
