apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.slurmEpilog }}
data:
  UbiqFinish.sh: |
    #!/bin/bash
    ID_DIR="/mnt/identity-store"
    rm -f "$ID_DIR/${SLURM_JOB_ID}.passwd" "$ID_DIR/${SLURM_JOB_ID}.group"

