apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-prolog-script
  namespace: hpc-ubiq
data:
  export-user-identity.sh: |
    #!/bin/bash
    ID_DIR="/mnt/identity-store"

    UID=$(id -u "$SLURM_JOB_USER")
    GID=$(id -g "$SLURM_JOB_USER")
    HOME="/home/$SLURM_JOB_USER"

    echo "$SLURM_JOB_USER:x:$UID:$GID:$SLURM_JOB_USER:$HOME:/bin/bash" > "$ID_DIR/${SLURM_JOB_ID}.passwd"
    echo "users:x:$GID:" > "$ID_DIR/${SLURM_JOB_ID}.group"
