apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: login-debug
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: login-debug
    spec:
      initContainers:
      - name: ad-join-init-container
        image: ubiquitycluster/slurm-adcli:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Reading SSSD credentials from secret..."
            domain="campus.unn.ac.uk"
            username="HPC_ServiceAccount"
            password="Silicon-D1oxide"
            echo "Joining AD domain $domain as $username..."
            echo $password | adcli -v join --domain-ou=OU=HPC_Devices,OU=Servers,DC=campus,DC=unn,DC=ac,DC=uk $domain --login-user=$username --stdin-password && \
            mv /etc/krb5.keytab /keytab/keytab
        volumeMounts:
        - name: keytab-volume
          mountPath: /keytab
        - name: sssd-creds
          mountPath: /etc/sssd-creds

      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /var/lib/sss/pipes/private;
          chmod 1755 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir

      containers:
      - name: login
        image: ubiquitycluster/slurm-login:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm/slurm.conf
          subPath: slurm.conf
        - name: munge-key
          mountPath: /tmp/munge.key
          subPath: munge.key
        - name: sssd-config
          mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
        - name: sssd-dir
          mountPath: /var/lib/sss/pipes
        - name: krb5-config
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: keytab-volume
          mountPath: /etc/krb5.keytab
          subPath: keytab
      volumes:
      - name: slurm-config
        configMap:
          name: slurm-conf
      - name: munge-key
        secret:
          secretName: munge-key
          defaultMode: 0400
      - name: sssd-config
        configMap:
          name: sssd-config
          defaultMode: 0600
      - name: krb5-config
        configMap:
          name: krb5-config
      - name: sssd-creds
        secret:
          secretName: sssd-creds
      - name: keytab-volume
        emptyDir: {}
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubiq-sssd
          type: DirectoryOrCreate
